# {{ ansible_managed }}
apiVersion: 1
deleteDatasources:
  - name: Prometheus
    orgId: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://192.168.50.249:9090
    isDefault: true
    editable: true
