---
prometheus_web_listen_address: "0.0.0.0:9090"
prometheus_storage_retention: "30d"
prometheus_scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
          - "localhost:9090"
  - job_name: "node"
    file_sd_configs:
      - files:
          - "{{ prometheus_config_dir }}/file_sd/node.yml"
prometheus_alertmanager_config:
  - static_configs:
      - targets:
          - "localhost:9093"
prometheus_config_file: "prometheus.yml.j2"
