---
# prometheus.yml
prometheus_scrape_interval: 15s
prometheus_evaluation_interval: 60s
alertmanager_target: localhost:9093

# Self-scrape
prometheus_self_target: localhost:9090

# PVE
pve_node_exporter_targets:
  - pve0:9100
  - pve1:9100
  - pve2:9100
  - pve3:9100
  - pve4:9100
pve_exporter_target: pve0
pve_exporter_endpoint: prometheus-pve-exporter:9221
scaphandre_targets:
  - host: pve0
  - host: pve1
  - host: pve2
  - host: pve3
  - host: pve4

# Network
openwrt_targets:
  - ap:9100
  - repeater:9100
opnsense_targets:
  - opnsense:9100

# MikroTik SNMP
mikrotik_host: 192.168.10.5
snmp_exporter_endpoint: portainer.home:9116

# Blackbox
blackbox_targets:
  - https://blog.vincentdupain.com

# Home Assistant
hass_host: homeassistant:8123